version: '3.7'

services:
  ts-node-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: eu-pescador-wiki
    env_file: .env
    expose:
      - '4002'
    ports:
      - '4002:4002'
    command: bash -c "npm run migration:run  && npm run dev"
    depends_on:
      - db
  db:
    container_name: "postgresDbWiki"
    image: "postgres:latest"
    ports: 
      - "5433:5433"
    volumes:
      - db_persdata:/var/lib/db
    command: postgres -c port=5433
    env_file: .env
    networks:
      - default
networks:
  default:
volumes:
  db_persdata : {}
